### ISSUE TITLE
SSL connection error

### ISSUE THREAD

**Issue by rakvium** [NARKOZ/apluscard#1]
In the middle of April, 2015 AzeriCard switched from SSLv3 to TLSv1 and changed their certificate.
As for now, all POST requests for process Azericard payment being failed with `response_code: 0` and `return_code: :ssl_connection_error`.

**Comment by NARKOZ** [comment]
I don't know why it is failing. I also can't debug as I currently don't have access to the sandbox, sorry.

**Comment by NARKOZ** [comment]
Version 1.0.2 was released with a fix.
